-- =============================================================================
-- 03: CURATED schema - Dynamic Tables
-- =============================================================================
USE SCHEMA RISK_COPILOT.CURATED;

-- DT_ACCOUNT_SIGNALS: Per-account fraud/AML behavioural signals
CREATE OR REPLACE DYNAMIC TABLE DT_ACCOUNT_SIGNALS
    TARGET_LAG = '15 minutes'
    WAREHOUSE = COMPUTE_WH
    COMMENT = 'Per-account fraud/AML behavioural signals over trailing windows relative to latest transaction time'
AS
WITH ref_ts AS (SELECT MAX(TXN_TS) AS T FROM RISK_COPILOT.RAW.TRANSACTIONS),
t AS (SELECT x.*, r0.T FROM RISK_COPILOT.RAW.TRANSACTIONS x CROSS JOIN ref_ts r0),
w48 AS (
  SELECT ACCOUNT_ID,
    COUNT_IF(DIRECTION='CREDIT') AS INFLOW_CNT_48H,
    COUNT(DISTINCT IFF(DIRECTION='CREDIT', COUNTERPARTY_ACCOUNT_ID, NULL)) AS DISTINCT_REMITTERS_48H,
    SUM(IFF(DIRECTION='CREDIT', AMOUNT_INR, 0)) AS INFLOW_AMT_48H,
    SUM(IFF(DIRECTION='DEBIT', AMOUNT_INR, 0)) AS OUTFLOW_AMT_48H,
    SUM(IFF(DIRECTION='DEBIT' AND CHANNEL IN ('RTGS','NEFT'), AMOUNT_INR, 0)) AS RTGS_NEFT_OUT_48H,
    COUNT(DISTINCT DEVICE_ID) AS DISTINCT_DEVICES_48H,
    COUNT_IF(GEO_COUNTRY <> 'IN' OR IP_ADDRESS LIKE '185.%') AS FOREIGN_OR_RISKY_IP_TXNS_48H
  FROM t WHERE TXN_TS >= DATEADD(hour, -48, T) GROUP BY 1),
prior AS (
  SELECT ACCOUNT_ID, MAX(IFF(TXN_TS < DATEADD(hour,-48,T), TXN_TS, NULL)) AS LAST_TXN_BEFORE_WINDOW FROM t GROUP BY 1),
struct AS (
  SELECT ACCOUNT_ID, COUNT(*) AS CASH_NEAR_CTR_10D, SUM(AMOUNT_INR) AS CASH_NEAR_CTR_AMT_10D
  FROM t WHERE CHANNEL='CASH' AND DIRECTION='CREDIT' AND AMOUNT_INR BETWEEN 900000 AND 999999 AND TXN_TS >= DATEADD(day,-10,T) GROUP BY 1),
big AS (SELECT * FROM t WHERE DIRECTION='DEBIT' AND CHANNEL IN ('NEFT','RTGS') AND AMOUNT_INR >= 1000000 AND TXN_TS >= DATEADD(day,-7,T)),
cyc AS (
  SELECT a.ACCOUNT_ID A1, b.ACCOUNT_ID A2, c.ACCOUNT_ID A3, a.AMOUNT_INR AMT
  FROM big a JOIN big b ON a.COUNTERPARTY_ACCOUNT_ID=b.ACCOUNT_ID AND b.TXN_TS > a.TXN_TS
    JOIN big c ON b.COUNTERPARTY_ACCOUNT_ID=c.ACCOUNT_ID AND c.TXN_TS > b.TXN_TS AND c.COUNTERPARTY_ACCOUNT_ID=a.ACCOUNT_ID
  WHERE c.TXN_TS <= DATEADD(hour,72,a.TXN_TS) AND ABS(a.AMOUNT_INR - c.AMOUNT_INR) <= 0.1*a.AMOUNT_INR),
rt AS (
  SELECT ACCOUNT_ID, COUNT(*) ROUND_TRIP_CYCLES_7D, MAX(AMT) ROUND_TRIP_AMT, ARRAY_AGG(DISTINCT RING) ROUND_TRIP_RING
  FROM (SELECT A1 ACCOUNT_ID, AMT, A1||'>'||A2||'>'||A3 RING FROM cyc UNION ALL SELECT A2, AMT, A1||'>'||A2||'>'||A3 FROM cyc UNION ALL SELECT A3, AMT, A1||'>'||A2||'>'||A3 FROM cyc)
  GROUP BY 1)
SELECT acc.ACCOUNT_ID, acc.CUSTOMER_ID, acc.ACCOUNT_TYPE, acc.OPEN_DATE, c.FULL_NAME, c.SEGMENT, c.KYC_RISK_RATING, c.OCCUPATION, c.DECLARED_ANNUAL_INCOME, c.IS_PEP, c.CITY,
  DATEDIFF(day, acc.OPEN_DATE, (SELECT T FROM ref_ts)) AS ACCOUNT_AGE_DAYS,
  DATEDIFF(day, p.LAST_TXN_BEFORE_WINDOW, DATEADD(hour,-48,(SELECT T FROM ref_ts))) AS DORMANT_DAYS_BEFORE_WINDOW,
  COALESCE(w.INFLOW_CNT_48H,0) INFLOW_CNT_48H, COALESCE(w.DISTINCT_REMITTERS_48H,0) DISTINCT_REMITTERS_48H,
  COALESCE(w.INFLOW_AMT_48H,0) INFLOW_AMT_48H, COALESCE(w.OUTFLOW_AMT_48H,0) OUTFLOW_AMT_48H, COALESCE(w.RTGS_NEFT_OUT_48H,0) RTGS_NEFT_OUT_48H,
  IFF(COALESCE(w.INFLOW_AMT_48H,0)>0, ROUND(w.OUTFLOW_AMT_48H / w.INFLOW_AMT_48H,3), NULL) AS PASS_THROUGH_RATIO_48H,
  COALESCE(w.DISTINCT_DEVICES_48H,0) DISTINCT_DEVICES_48H, COALESCE(w.FOREIGN_OR_RISKY_IP_TXNS_48H,0) FOREIGN_OR_RISKY_IP_TXNS_48H,
  COALESCE(s.CASH_NEAR_CTR_10D,0) CASH_NEAR_CTR_10D, COALESCE(s.CASH_NEAR_CTR_AMT_10D,0) CASH_NEAR_CTR_AMT_10D,
  COALESCE(r.ROUND_TRIP_CYCLES_7D,0) ROUND_TRIP_CYCLES_7D, r.ROUND_TRIP_AMT, r.ROUND_TRIP_RING,
  wl.LIST_NAME AS WATCHLIST_HIT, wl.MATCH_SCORE AS WATCHLIST_SCORE,
  (SELECT T FROM ref_ts) AS SIGNAL_AS_OF
FROM RISK_COPILOT.RAW.ACCOUNTS acc
JOIN RISK_COPILOT.RAW.CUSTOMERS c ON c.CUSTOMER_ID=acc.CUSTOMER_ID
LEFT JOIN prior p ON p.ACCOUNT_ID=acc.ACCOUNT_ID
LEFT JOIN w48 w ON w.ACCOUNT_ID=acc.ACCOUNT_ID
LEFT JOIN struct s ON s.ACCOUNT_ID=acc.ACCOUNT_ID
LEFT JOIN rt r ON r.ACCOUNT_ID=acc.ACCOUNT_ID
LEFT JOIN (SELECT MATCHED_CUSTOMER_ID, LIST_NAME, MATCH_SCORE FROM RISK_COPILOT.RAW.WATCHLIST WHERE LIST_NAME NOT LIKE 'PEP%' QUALIFY ROW_NUMBER() OVER (PARTITION BY MATCHED_CUSTOMER_ID ORDER BY MATCH_SCORE DESC)=1) wl ON wl.MATCHED_CUSTOMER_ID=c.CUSTOMER_ID
WHERE acc.ACCOUNT_TYPE <> 'LOAN';


-- DT_FRAUD_ALERTS: Rule-based, explainable fraud/AML alerts
CREATE OR REPLACE DYNAMIC TABLE DT_FRAUD_ALERTS
    TARGET_LAG = '15 minutes'
    WAREHOUSE = COMPUTE_WH
    COMMENT = 'Rule-based, explainable fraud/AML alerts. Each red flag maps to an internal policy section.'
AS
WITH f AS (
  SELECT s.*,
    ARRAY_COMPACT(ARRAY_CONSTRUCT(
      IFF((ACCOUNT_AGE_DAYS <= 180 OR DORMANT_DAYS_BEFORE_WINDOW >= 30) AND INFLOW_CNT_48H >= 10, OBJECT_CONSTRUCT('flag','NEW_OR_DORMANT_BURST','policy','AML-POL 4.2(a)','weight',20,'evidence', 'age '||ACCOUNT_AGE_DAYS||'d, dormant '||COALESCE(DORMANT_DAYS_BEFORE_WINDOW::STRING,'n/a')||'d, '||INFLOW_CNT_48H||' credits/48h'), NULL),
      IFF(DISTINCT_REMITTERS_48H >= 15, OBJECT_CONSTRUCT('flag','MANY_REMITTERS','policy','AML-POL 4.2(b)','weight',20,'evidence', DISTINCT_REMITTERS_48H||' distinct remitters in 48h'), NULL),
      IFF(PASS_THROUGH_RATIO_48H >= 0.8 AND INFLOW_AMT_48H >= 200000, OBJECT_CONSTRUCT('flag','RAPID_PASS_THROUGH','policy','AML-POL 4.2(c)','weight',25,'evidence', ROUND(PASS_THROUGH_RATIO_48H*100)||'% of INR '||ROUND(INFLOW_AMT_48H)||' moved out'), NULL),
      IFF(DISTINCT_DEVICES_48H >= 4 OR FOREIGN_OR_RISKY_IP_TXNS_48H >= 5, OBJECT_CONSTRUCT('flag','DEVICE_IP_ANOMALY','policy','AML-POL 4.2(d)','weight',10,'evidence', DISTINCT_DEVICES_48H||' devices, '||FOREIGN_OR_RISKY_IP_TXNS_48H||' foreign/risky-IP txns'), NULL),
      IFF(INFLOW_AMT_48H > DECLARED_ANNUAL_INCOME * 0.5, OBJECT_CONSTRUCT('flag','PROFILE_MISMATCH','policy','AML-POL 4.2(e)','weight',10,'evidence', 'INR '||ROUND(INFLOW_AMT_48H)||' in 48h vs declared income INR '||DECLARED_ANNUAL_INCOME||' ('||OCCUPATION||')'), NULL),
      IFF(CASH_NEAR_CTR_10D >= 3, OBJECT_CONSTRUCT('flag','STRUCTURING','policy','AML-POL 4.3','weight',35,'evidence', CASH_NEAR_CTR_10D||' cash deposits of INR 9-10 lakh in 10 days, total INR '||ROUND(CASH_NEAR_CTR_AMT_10D)), NULL),
      IFF(ROUND_TRIP_CYCLES_7D >= 1, OBJECT_CONSTRUCT('flag','ROUND_TRIPPING','policy','AML-POL 4.4','weight',35,'evidence', 'Circular flow of ~INR '||ROUND(ROUND_TRIP_AMT)||' completed within 72h: '||ARRAY_TO_STRING(ROUND_TRIP_RING,'; ')), NULL),
      IFF(WATCHLIST_SCORE >= 0.85, OBJECT_CONSTRUCT('flag','SANCTIONS_WATCHLIST_HIT','policy','AML-POL 7.1','weight',30,'evidence', WATCHLIST_HIT||' match score '||WATCHLIST_SCORE), NULL),
      IFF(IS_PEP AND INFLOW_AMT_48H > 0, OBJECT_CONSTRUCT('flag','PEP_ACTIVITY','policy','AML-POL 3.1','weight',10,'evidence','Customer is a PEP'), NULL)
    )) AS RED_FLAGS
  FROM RISK_COPILOT.CURATED.DT_ACCOUNT_SIGNALS s),
g AS (SELECT f.*, TRANSFORM(RED_FLAGS, x -> x:flag::STRING) AS FLAG_NAMES FROM f)
SELECT 'ALR-' || ACCOUNT_ID AS ALERT_ID, ACCOUNT_ID, CUSTOMER_ID, FULL_NAME, SEGMENT, KYC_RISK_RATING, OCCUPATION,
  RED_FLAGS, FLAG_NAMES, ARRAY_SIZE(RED_FLAGS) AS RED_FLAG_COUNT,
  LEAST(100, REDUCE(RED_FLAGS, 0, (acc, x) -> acc + x:weight::NUMBER) + IFF(KYC_RISK_RATING='HIGH',10,0)) AS RISK_SCORE,
  CASE
    WHEN ARRAY_CONTAINS('STRUCTURING'::VARIANT, FLAG_NAMES) OR ARRAY_CONTAINS('ROUND_TRIPPING'::VARIANT, FLAG_NAMES) THEN 'AML_LAYERING'
    WHEN ARRAY_SIZE(RED_FLAGS) >= 2 AND ARRAY_CONTAINS('RAPID_PASS_THROUGH'::VARIANT, FLAG_NAMES) THEN 'MONEY_MULE'
    WHEN ARRAY_CONTAINS('SANCTIONS_WATCHLIST_HIT'::VARIANT, FLAG_NAMES) THEN 'SANCTIONS'
    ELSE 'OTHER' END AS TYPOLOGY,
  CASE WHEN ARRAY_CONTAINS('SANCTIONS_WATCHLIST_HIT'::VARIANT, FLAG_NAMES) OR REDUCE(RED_FLAGS, 0, (acc, x) -> acc + x:weight::NUMBER) >= 60 THEN 'FREEZE_ACCOUNT'
       WHEN REDUCE(RED_FLAGS, 0, (acc, x) -> acc + x:weight::NUMBER) >= 35 THEN 'PLACE_HOLD'
       WHEN REDUCE(RED_FLAGS, 0, (acc, x) -> acc + x:weight::NUMBER) >= 20 THEN 'STEP_UP_AUTH'
       ELSE 'REVIEW_AND_CLEAR' END AS RECOMMENDED_ACTION,
  INFLOW_AMT_48H, OUTFLOW_AMT_48H, PASS_THROUGH_RATIO_48H, CASH_NEAR_CTR_AMT_10D, ROUND_TRIP_AMT, SIGNAL_AS_OF
FROM g WHERE ARRAY_SIZE(RED_FLAGS) >= 2 OR ARRAY_CONTAINS('SANCTIONS_WATCHLIST_HIT'::VARIANT, FLAG_NAMES) OR ARRAY_CONTAINS('STRUCTURING'::VARIANT, FLAG_NAMES) OR ARRAY_CONTAINS('ROUND_TRIPPING'::VARIANT, FLAG_NAMES);


-- DT_LCR_DAILY: Basel III Liquidity Coverage Ratio
CREATE OR REPLACE DYNAMIC TABLE DT_LCR_DAILY
    TARGET_LAG = '1 hour'
    WAREHOUSE = COMPUTE_WH
    COMMENT = 'Daily Basel III LCR with haircuts, L2 (40%) and L2B (15%) caps, 75% inflow cap; internal floor 110% (ALM-POL 5.1)'
AS
WITH h AS (
  SELECT AS_OF_DATE,
    SUM(IFF(HQLA_LEVEL='LEVEL_1', MARKET_VALUE_INR*(1-HAIRCUT),0)) L1,
    SUM(IFF(HQLA_LEVEL='LEVEL_2A', MARKET_VALUE_INR*(1-HAIRCUT),0)) L2A,
    SUM(IFF(HQLA_LEVEL='LEVEL_2B', MARKET_VALUE_INR*(1-HAIRCUT),0)) L2B
  FROM RISK_COPILOT.RAW.HQLA_HOLDINGS GROUP BY 1),
hc AS (
  SELECT AS_OF_DATE, L1, L2A, L2B,
    LEAST(L2B, 15/85*(L1+L2A)) L2B_ADJ, LEAST(L2A + LEAST(L2B, 15/85*(L1+L2A)), 2/3*L1) L2_ADJ FROM h),
cf AS (
  SELECT AS_OF_DATE,
    SUM(IFF(FLOW_TYPE='OUTFLOW', BALANCE_INR*RATE,0)) OUTFLOWS,
    SUM(IFF(FLOW_TYPE='INFLOW', BALANCE_INR*RATE,0)) INFLOWS_RAW,
    SUM(IFF(FLOW_TYPE='OUTFLOW' AND CATEGORY LIKE 'Retail%', BALANCE_INR,0)) RETAIL_DEPOSITS,
    SUM(IFF(FLOW_TYPE='OUTFLOW' AND BUCKET='1-7D', BALANCE_INR*RATE,0)) - SUM(IFF(FLOW_TYPE='INFLOW' AND BUCKET='1-7D', BALANCE_INR*RATE,0)) NET_OUT_1_7D,
    SUM(IFF(FLOW_TYPE='OUTFLOW' AND BUCKET='8-14D', BALANCE_INR*RATE,0)) - SUM(IFF(FLOW_TYPE='INFLOW' AND BUCKET='8-14D', BALANCE_INR*RATE,0)) NET_OUT_8_14D,
    SUM(IFF(FLOW_TYPE='OUTFLOW' AND BUCKET='15-30D', BALANCE_INR*RATE,0)) - SUM(IFF(FLOW_TYPE='INFLOW' AND BUCKET='15-30D', BALANCE_INR*RATE,0)) NET_OUT_15_30D
  FROM RISK_COPILOT.RAW.CASHFLOW_POSITIONS GROUP BY 1)
SELECT hc.AS_OF_DATE, ROUND(hc.L1) L1_HQLA, ROUND(hc.L2A) L2A_HQLA_POST_HAIRCUT, ROUND(hc.L2B) L2B_HQLA_POST_HAIRCUT,
  ROUND(hc.L1 + hc.L2_ADJ) AS HQLA_STOCK,
  ROUND(cf.OUTFLOWS) GROSS_OUTFLOWS, ROUND(LEAST(cf.INFLOWS_RAW, 0.75*cf.OUTFLOWS)) CAPPED_INFLOWS,
  ROUND(cf.OUTFLOWS - LEAST(cf.INFLOWS_RAW, 0.75*cf.OUTFLOWS)) NET_CASH_OUTFLOWS_30D,
  ROUND(100*(hc.L1 + hc.L2_ADJ)/(cf.OUTFLOWS - LEAST(cf.INFLOWS_RAW, 0.75*cf.OUTFLOWS)),1) AS LCR_PCT,
  ROUND(cf.NET_OUT_1_7D) NET_OUT_1_7D, ROUND(cf.NET_OUT_8_14D) NET_OUT_8_14D, ROUND(cf.NET_OUT_15_30D) NET_OUT_15_30D,
  ROUND(100*(hc.L1 + LEAST(hc.L2A*0.7 + hc.L2B_ADJ, 2/3*hc.L1)) /
        (cf.OUTFLOWS + 0.15*cf.RETAIL_DEPOSITS - LEAST(cf.INFLOWS_RAW, 0.75*(cf.OUTFLOWS + 0.15*cf.RETAIL_DEPOSITS))),1) AS LCR_STRESS_S1_PCT,
  CASE WHEN 100*(hc.L1 + hc.L2_ADJ)/(cf.OUTFLOWS - LEAST(cf.INFLOWS_RAW, 0.75*cf.OUTFLOWS)) < 100 THEN 'REGULATORY_BREACH'
       WHEN 100*(hc.L1 + hc.L2_ADJ)/(cf.OUTFLOWS - LEAST(cf.INFLOWS_RAW, 0.75*cf.OUTFLOWS)) < 110 THEN 'RED_CFP_TRIGGER'
       WHEN 100*(hc.L1 + hc.L2_ADJ)/(cf.OUTFLOWS - LEAST(cf.INFLOWS_RAW, 0.75*cf.OUTFLOWS)) < 115 THEN 'AMBER_ALCO'
       ELSE 'GREEN' END AS LCR_STATUS
FROM hc JOIN cf USING (AS_OF_DATE);


-- DT_LOAN_EWS: Credit Early Warning System
CREATE OR REPLACE DYNAMIC TABLE DT_LOAN_EWS
    TARGET_LAG = '1 hour'
    WAREHOUSE = COMPUTE_WH
    COMMENT = 'Credit EWS: SMA/NPA classification (CR-POL 4.1), IFRS9 stage, EWS triggers and actions (CR-POL 5.3)'
AS
WITH b AS (
 SELECT l.*, c.FULL_NAME,
  CASE WHEN DPD = 0 THEN 'STANDARD' WHEN DPD <= 30 THEN 'SMA-0' WHEN DPD <= 60 THEN 'SMA-1' WHEN DPD <= 90 THEN 'SMA-2' ELSE 'NPA' END AS ASSET_CLASS,
  CASE WHEN DPD > 90 THEN 'STAGE_3' WHEN DPD >= 30 THEN 'STAGE_2' ELSE 'STAGE_1' END AS IFRS9_STAGE,
  ARRAY_COMPACT(ARRAY_CONSTRUCT(
    IFF(UTILIZATION_PCT > 90, 'HIGH_UTILISATION ('||UTILIZATION_PCT||'%)', NULL),
    IFF(NACH_BOUNCES_90D >= 2, 'NACH_BOUNCES ('||NACH_BOUNCES_90D||' in 90d)', NULL),
    IFF(SALES_VELOCITY_CHG_PCT <= -30, 'SALES_VELOCITY_DROP ('||SALES_VELOCITY_CHG_PCT||'%)', NULL),
    IFF(BUREAU_SCORE < 600, 'LOW_BUREAU_SCORE ('||BUREAU_SCORE||')', NULL))) AS EWS_TRIGGERS
 FROM RISK_COPILOT.RAW.LOANS l JOIN RISK_COPILOT.RAW.CUSTOMERS c USING (CUSTOMER_ID))
SELECT b.*, ARRAY_SIZE(EWS_TRIGGERS) AS EWS_TRIGGER_COUNT,
  CASE WHEN ASSET_CLASS='NPA' THEN 'NPA_RECOVERY_AND_PROVISIONING'
       WHEN ARRAY_SIZE(EWS_TRIGGERS) >= 3 OR ASSET_CLASS='SMA-2' THEN 'RESTRUCTURING_DISCUSSION_CREDIT_COMMITTEE'
       WHEN ARRAY_SIZE(EWS_TRIGGERS) = 2 THEN 'LIMIT_FREEZE_AND_COLLATERAL_REVALUATION'
       WHEN ARRAY_SIZE(EWS_TRIGGERS) = 1 OR ASSET_CLASS IN ('SMA-0','SMA-1') THEN 'WATCHLIST'
       ELSE 'NO_ACTION' END AS EWS_ACTION,
  'CR-POL 4.1 / CR-POL 5.3' AS POLICY_REF
FROM b;
