-- =============================================================================
-- 04: CURATED schema - Views
-- =============================================================================
USE SCHEMA RISK_COPILOT.CURATED;

CREATE OR REPLACE VIEW V_EXECUTIVE_SUMMARY AS
SELECT
  (SELECT COUNT(*) FROM RISK_COPILOT.CURATED.DT_FRAUD_ALERTS) AS TOTAL_OPEN_ALERTS,
  (SELECT COUNT(*) FROM RISK_COPILOT.CURATED.DT_FRAUD_ALERTS WHERE RECOMMENDED_ACTION = 'FREEZE_ACCOUNT') AS CRITICAL_FREEZE_ALERTS,
  (SELECT SUM(OUTFLOW_AMT_48H) FROM RISK_COPILOT.CURATED.DT_FRAUD_ALERTS) AS TOTAL_48H_OUTFLOW_EXPOSURE_INR,
  (SELECT COUNT(*) FROM RISK_COPILOT.APP.CASES WHERE STATUS = 'PENDING_REVIEW') AS PENDING_SAR_CASES,
  (SELECT COUNT(*) FROM RISK_COPILOT.APP.CASES WHERE STATUS = 'APPROVED_FOR_FILING') AS FILED_SAR_CASES,
  (SELECT LCR_PCT FROM RISK_COPILOT.CURATED.DT_LCR_DAILY ORDER BY AS_OF_DATE DESC LIMIT 1) AS LATEST_LCR_PCT,
  (SELECT LCR_STATUS FROM RISK_COPILOT.CURATED.DT_LCR_DAILY ORDER BY AS_OF_DATE DESC LIMIT 1) AS LATEST_LCR_STATUS,
  (SELECT ROUND(100 * SUM(IFF(DPD > 90, OUTSTANDING, 0)) / SUM(OUTSTANDING), 2) FROM RISK_COPILOT.CURATED.DT_LOAN_EWS) AS GROSS_NPA_PCT,
  (SELECT SUM(IFF(DPD BETWEEN 1 AND 90, OUTSTANDING, 0)) FROM RISK_COPILOT.CURATED.DT_LOAN_EWS) AS SMA_EXPOSURE_INR;


CREATE OR REPLACE VIEW V_INDUSTRY_CONCENTRATION AS
SELECT INDUSTRY, COUNT(*) LOANS, SUM(OUTSTANDING) OUTSTANDING_INR,
  ROUND(100*SUM(OUTSTANDING)/SUM(SUM(OUTSTANDING)) OVER (),2) SHARE_PCT,
  IFF(INDUSTRY IN ('Real Estate','NBFC Lending'), 10, 15) AS LIMIT_PCT,
  IFF(100*SUM(OUTSTANDING)/SUM(SUM(OUTSTANDING)) OVER () > IFF(INDUSTRY IN ('Real Estate','NBFC Lending'), 10, 15), 'BREACH','WITHIN_LIMIT') AS STATUS,
  'CR-POL 7.1' POLICY_REF
FROM RISK_COPILOT.RAW.LOANS GROUP BY INDUSTRY;


CREATE OR REPLACE VIEW V_NETWORK_GRAPH AS
WITH links AS (
  SELECT
    t.ACCOUNT_ID AS SOURCE_NODE, a1.CUSTOMER_ID AS SOURCE_CUST_ID, c1.FULL_NAME AS SOURCE_NAME,
    t.COUNTERPARTY_ACCOUNT_ID AS TARGET_NODE, COALESCE(a2.CUSTOMER_ID, t.COUNTERPARTY_ACCOUNT_ID) AS TARGET_CUST_ID,
    COALESCE(c2.FULL_NAME, t.COUNTERPARTY_ACCOUNT_ID) AS TARGET_NAME,
    'TRANSACTION_FLOW' AS LINK_TYPE,
    COUNT(*) AS TXN_COUNT, SUM(t.AMOUNT_INR) AS TOTAL_VOLUME_INR, MAX(t.TXN_TS) AS LAST_ACTIVITY
  FROM RISK_COPILOT.RAW.TRANSACTIONS t
  LEFT JOIN RISK_COPILOT.RAW.ACCOUNTS a1 ON a1.ACCOUNT_ID = t.ACCOUNT_ID
  LEFT JOIN RISK_COPILOT.RAW.CUSTOMERS c1 ON c1.CUSTOMER_ID = a1.CUSTOMER_ID
  LEFT JOIN RISK_COPILOT.RAW.ACCOUNTS a2 ON a2.ACCOUNT_ID = t.COUNTERPARTY_ACCOUNT_ID
  LEFT JOIN RISK_COPILOT.RAW.CUSTOMERS c2 ON c2.CUSTOMER_ID = a2.CUSTOMER_ID
  WHERE t.SYNTH_LABEL <> 'NORMAL'
  GROUP BY 1,2,3,4,5,6,7
  UNION ALL
  SELECT
    t1.ACCOUNT_ID AS SOURCE_NODE, a1.CUSTOMER_ID AS SOURCE_CUST_ID, c1.FULL_NAME AS SOURCE_NAME,
    t2.ACCOUNT_ID AS TARGET_NODE, a2.CUSTOMER_ID AS TARGET_CUST_ID, c2.FULL_NAME AS TARGET_NAME,
    'SHARED_DEVICE (' || t1.DEVICE_ID || ')' AS LINK_TYPE,
    COUNT(DISTINCT t1.DEVICE_ID) AS TXN_COUNT, SUM(t1.AMOUNT_INR + t2.AMOUNT_INR) / 2 AS TOTAL_VOLUME_INR, MAX(GREATEST(t1.TXN_TS, t2.TXN_TS)) AS LAST_ACTIVITY
  FROM RISK_COPILOT.RAW.TRANSACTIONS t1
  JOIN RISK_COPILOT.RAW.TRANSACTIONS t2 ON t1.DEVICE_ID = t2.DEVICE_ID AND t1.ACCOUNT_ID < t2.ACCOUNT_ID AND t1.DEVICE_ID NOT IN ('BRANCH', 'BRANCH-COUNTER')
  JOIN RISK_COPILOT.RAW.ACCOUNTS a1 ON a1.ACCOUNT_ID = t1.ACCOUNT_ID
  JOIN RISK_COPILOT.RAW.CUSTOMERS c1 ON c1.CUSTOMER_ID = a1.CUSTOMER_ID
  JOIN RISK_COPILOT.RAW.ACCOUNTS a2 ON a2.ACCOUNT_ID = t2.ACCOUNT_ID
  JOIN RISK_COPILOT.RAW.CUSTOMERS c2 ON c2.CUSTOMER_ID = a2.CUSTOMER_ID
  GROUP BY 1,2,3,4,5,6,7
)
SELECT * FROM links;


CREATE OR REPLACE VIEW V_RECENT_HIGH_RISK_TXNS AS
SELECT
  t.TXN_ID, t.TXN_TS, t.ACCOUNT_ID, c.CUSTOMER_ID, c.FULL_NAME AS CUSTOMER_NAME,
  t.COUNTERPARTY_ACCOUNT_ID, t.CHANNEL, t.DIRECTION, t.AMOUNT_INR,
  a.RISK_SCORE, a.TYPOLOGY, a.RECOMMENDED_ACTION, a.RED_FLAGS AS EVIDENCE_FLAGS
FROM RISK_COPILOT.RAW.TRANSACTIONS t
JOIN RISK_COPILOT.CURATED.DT_FRAUD_ALERTS a ON a.ACCOUNT_ID = t.ACCOUNT_ID
JOIN RISK_COPILOT.RAW.CUSTOMERS c ON c.CUSTOMER_ID = a.CUSTOMER_ID
WHERE t.TXN_TS >= DATEADD(hour, -48, (SELECT MAX(TXN_TS) FROM RISK_COPILOT.RAW.TRANSACTIONS))
  AND a.RISK_SCORE >= 45
ORDER BY a.RISK_SCORE DESC, t.TXN_TS DESC;


CREATE OR REPLACE VIEW V_RISK_CASE_SUMMARY AS
SELECT c.CASE_ID,c.FINDING_ID,c.ALERT_ID,c.ACCOUNT_ID,c.CUSTOMER_ID,
       c.CASE_TYPE,c.PRIORITY,c.STATUS,c.SUMMARY,c.EVIDENCE_COUNT,
       c.CREATED_BY,c.CREATED_AT,f.RISK_SCORE,f.SEVERITY,f.FINDING_TYPE
FROM EVIDENCE.INVESTIGATION_CASES c
LEFT JOIN EVIDENCE.RISK_FINDINGS f ON f.FINDING_ID=c.FINDING_ID;


CREATE OR REPLACE VIEW V_RISK_COPILOT_EVIDENCE AS
SELECT FINDING_ID, ALERT_ID, ACCOUNT_ID, CUSTOMER_ID, EVIDENCE_ID,
       EVIDENCE_TYPE, SOURCE_OBJECT, SOURCE_RECORD_ID, EVIDENCE_TEXT,
       POLICY_ID, REGULATION_ID, RULE_ID, CONFIDENCE, EVENT_TS
FROM EVIDENCE.RISK_EVIDENCE;


CREATE OR REPLACE VIEW V_RISK_COPILOT_FINDINGS AS
SELECT FINDING_ID, ALERT_ID, ACCOUNT_ID, CUSTOMER_ID, FINDING_TYPE,
       SEVERITY, RISK_SCORE, FINDING_STATUS, SUMMARY,
       PRIMARY_POLICY_ID, PRIMARY_REGULATION_ID, EVIDENCE_COUNT,
       CONFIDENCE, MODEL_VERSION, CREATED_AT, UPDATED_AT
FROM EVIDENCE.RISK_FINDINGS;
