-- =============================================================================
-- 05: EVIDENCE schema - Tables & Stream
-- =============================================================================
USE SCHEMA RISK_COPILOT.EVIDENCE;

CREATE OR REPLACE TABLE RISK_FINDINGS (
    FINDING_ID VARCHAR DEFAULT 'FND-' || UUID_STRING(),
    ALERT_ID VARCHAR NOT NULL,
    ACCOUNT_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    FINDING_TYPE VARCHAR,
    SEVERITY VARCHAR,
    RISK_SCORE NUMBER(5,2),
    FINDING_STATUS VARCHAR DEFAULT 'OPEN',
    SUMMARY VARCHAR,
    PRIMARY_POLICY_ID VARCHAR,
    PRIMARY_REGULATION_ID VARCHAR,
    EVIDENCE_COUNT NUMBER(38,0) DEFAULT 0,
    CONFIDENCE NUMBER(5,2),
    MODEL_VERSION VARCHAR DEFAULT 'RULE_ENGINE_V1',
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RISK_EVIDENCE (
    EVIDENCE_ID VARCHAR DEFAULT 'EVD-' || UUID_STRING(),
    FINDING_ID VARCHAR,
    ALERT_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    EVIDENCE_TYPE VARCHAR,
    SOURCE_OBJECT VARCHAR,
    SOURCE_RECORD_ID VARCHAR,
    OBSERVED_VALUE VARIANT,
    EXPECTED_VALUE VARIANT,
    EVIDENCE_TEXT VARCHAR,
    POLICY_ID VARCHAR,
    REGULATION_ID VARCHAR,
    RULE_ID VARCHAR,
    CONFIDENCE NUMBER(5,2),
    EVENT_TS TIMESTAMP_NTZ,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR DEFAULT CURRENT_USER()
);

CREATE OR REPLACE TABLE INVESTIGATION_CASES (
    CASE_ID VARCHAR DEFAULT 'CASE-' || UUID_STRING(),
    FINDING_ID VARCHAR,
    ALERT_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    CASE_TYPE VARCHAR,
    PRIORITY VARCHAR,
    STATUS VARCHAR DEFAULT 'OPEN',
    SUMMARY VARCHAR,
    EVIDENCE_COUNT NUMBER(38,0),
    CREATED_BY VARCHAR,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE AUDIT_ACTIONS (
    ACTION_ID VARCHAR DEFAULT 'ACT-' || UUID_STRING(),
    CASE_ID VARCHAR,
    FINDING_ID VARCHAR,
    ACTION_TYPE VARCHAR,
    TARGET_SYSTEM VARCHAR,
    REQUESTED_BY VARCHAR,
    REQUESTED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    STATUS VARCHAR,
    RESULT VARIANT,
    ERROR_MESSAGE VARCHAR
);

-- Stream on RAW.TRANSACTIONS to trigger incremental task processing
CREATE OR REPLACE STREAM TRANSACTION_CHANGE_STREAM
    ON TABLE RISK_COPILOT.RAW.TRANSACTIONS
    APPEND_ONLY = TRUE;
