-- =============================================================================
-- 12: Tasks (Scheduled Automation)
-- =============================================================================
USE SCHEMA RISK_COPILOT.EVIDENCE;

-- Root task: Merge new fraud alerts into RISK_FINDINGS
-- Runs every 5 minutes, only when the stream has new data
CREATE OR REPLACE TASK T_BUILD_RISK_FINDINGS
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = '5 MINUTE'
    WHEN SYSTEM$STREAM_HAS_DATA('RISK_COPILOT.EVIDENCE.TRANSACTION_CHANGE_STREAM')
    OVERLAP_POLICY = NO_OVERLAP
AS
MERGE INTO EVIDENCE.RISK_FINDINGS tgt
USING (
  SELECT
    a.ALERT_ID,
    a.ACCOUNT_ID,
    a.CUSTOMER_ID,
    a.TYPOLOGY AS FINDING_TYPE,
    CASE
      WHEN a.RISK_SCORE >= 80 THEN 'CRITICAL'
      WHEN a.RISK_SCORE >= 60 THEN 'HIGH'
      WHEN a.RISK_SCORE >= 35 THEN 'MEDIUM'
      ELSE 'LOW'
    END AS SEVERITY,
    a.RISK_SCORE,
    'Potential ' || a.TYPOLOGY || ' risk detected for account ' ||
      a.ACCOUNT_ID || '. Red flags: ' ||
      ARRAY_TO_STRING(a.FLAG_NAMES, ', ') AS SUMMARY,
    ARRAY_SIZE(a.RED_FLAGS) AS EVIDENCE_COUNT,
    LEAST(99, 70 + ARRAY_SIZE(a.RED_FLAGS) * 5) AS CONFIDENCE,
    a.SIGNAL_AS_OF AS EVENT_TS
  FROM CURATED.DT_FRAUD_ALERTS a
  WHERE a.RISK_SCORE >= 35
) src
ON tgt.ALERT_ID = src.ALERT_ID
WHEN MATCHED THEN UPDATE SET
  tgt.ACCOUNT_ID = src.ACCOUNT_ID,
  tgt.CUSTOMER_ID = src.CUSTOMER_ID,
  tgt.FINDING_TYPE = src.FINDING_TYPE,
  tgt.SEVERITY = src.SEVERITY,
  tgt.RISK_SCORE = src.RISK_SCORE,
  tgt.SUMMARY = src.SUMMARY,
  tgt.EVIDENCE_COUNT = src.EVIDENCE_COUNT,
  tgt.CONFIDENCE = src.CONFIDENCE,
  tgt.UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN INSERT
  (ALERT_ID,ACCOUNT_ID,CUSTOMER_ID,FINDING_TYPE,SEVERITY,RISK_SCORE,
   SUMMARY,EVIDENCE_COUNT,CONFIDENCE)
VALUES
  (src.ALERT_ID,src.ACCOUNT_ID,src.CUSTOMER_ID,src.FINDING_TYPE,src.SEVERITY,
   src.RISK_SCORE,src.SUMMARY,src.EVIDENCE_COUNT,src.CONFIDENCE);


-- Child task: Build evidence rows from red flags (runs after T_BUILD_RISK_FINDINGS)
CREATE OR REPLACE TASK T_BUILD_EVIDENCE
    WAREHOUSE = COMPUTE_WH
    AFTER RISK_COPILOT.EVIDENCE.T_BUILD_RISK_FINDINGS
AS
INSERT INTO EVIDENCE.RISK_EVIDENCE
(
  FINDING_ID, ALERT_ID, ACCOUNT_ID, CUSTOMER_ID,
  EVIDENCE_TYPE, SOURCE_OBJECT, SOURCE_RECORD_ID,
  OBSERVED_VALUE, EVIDENCE_TEXT, POLICY_ID, RULE_ID,
  CONFIDENCE, EVENT_TS
)
SELECT
  f.FINDING_ID,
  a.ALERT_ID,
  a.ACCOUNT_ID,
  a.CUSTOMER_ID,
  x.value:flag::STRING,
  'RISK_COPILOT.CURATED.DT_FRAUD_ALERTS',
  a.ALERT_ID,
  x.value,
  x.value:evidence::STRING,
  x.value:policy::STRING,
  x.value:flag::STRING,
  f.CONFIDENCE,
  a.SIGNAL_AS_OF
FROM CURATED.DT_FRAUD_ALERTS a
JOIN EVIDENCE.RISK_FINDINGS f
  ON f.ALERT_ID = a.ALERT_ID,
LATERAL FLATTEN(input => a.RED_FLAGS) x
WHERE NOT EXISTS (
  SELECT 1
  FROM EVIDENCE.RISK_EVIDENCE e
  WHERE e.FINDING_ID = f.FINDING_ID
    AND e.EVIDENCE_TYPE = x.value:flag::STRING
);


-- Hourly auto-triage task (APP schema)
USE SCHEMA RISK_COPILOT.APP;

CREATE OR REPLACE TASK T_AUTO_TRIAGE
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = 'USING CRON 0 * * * * Asia/Kolkata'
    COMMENT = 'Hourly unattended fraud/AML triage + liquidity threshold monitoring'
AS
CALL RISK_COPILOT.APP.AUTO_TRIAGE(3);


-- Resume tasks (run these after initial setup)
-- ALTER TASK RISK_COPILOT.EVIDENCE.T_BUILD_EVIDENCE RESUME;
-- ALTER TASK RISK_COPILOT.EVIDENCE.T_BUILD_RISK_FINDINGS RESUME;
-- ALTER TASK RISK_COPILOT.APP.T_AUTO_TRIAGE RESUME;
