-- =============================================================================
-- 06: APP schema - Tables & Views
-- =============================================================================
USE SCHEMA RISK_COPILOT.APP;

CREATE OR REPLACE TABLE CASES (
    CASE_ID VARCHAR DEFAULT 'CASE-' || UUID_STRING(),
    ALERT_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    TYPOLOGY VARCHAR,
    RISK_SCORE NUMBER(38,0),
    STATUS VARCHAR DEFAULT 'OPEN',
    ASSIGNED_TO VARCHAR,
    ACTION_TAKEN VARCHAR,
    EVIDENCE VARIANT,
    POLICY_CITATIONS VARIANT,
    SAR_DRAFT VARCHAR,
    GUARDRAIL_RESULT VARIANT,
    MISSING_DOCS VARIANT,
    CREATED_BY VARCHAR DEFAULT CURRENT_USER(),
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    REVIEWED_BY VARCHAR,
    REVIEWED_AT TIMESTAMP_NTZ,
    REVIEW_DECISION VARCHAR,
    REVIEW_NOTES VARCHAR
);

CREATE OR REPLACE TABLE AUDIT_LOG (
    EVENT_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    EVENT_USER VARCHAR DEFAULT CURRENT_USER(),
    EVENT_ROLE VARCHAR DEFAULT CURRENT_ROLE(),
    EVENT_TYPE VARCHAR,
    OBJECT_ID VARCHAR,
    DETAILS VARIANT
);

-- Validation test suite view
CREATE OR REPLACE VIEW V_VALIDATION_TESTS AS
WITH truth AS (SELECT s.SCENARIO, a.ALERT_ID, a.TYPOLOGY FROM RISK_COPILOT.RAW.SYNTH_SCENARIOS s LEFT JOIN RISK_COPILOT.CURATED.DT_FRAUD_ALERTS a ON a.ACCOUNT_ID = s.ACCOUNT_ID),
lcr AS (SELECT * FROM RISK_COPILOT.CURATED.DT_LCR_DAILY)
SELECT 'DETECTION: mule recall' TEST, '12/12' EXPECTED, (SELECT COUNT_IF(TYPOLOGY='MONEY_MULE')||'/'||COUNT(*) FROM truth WHERE SCENARIO='MULE') ACTUAL
UNION ALL SELECT 'DETECTION: structuring recall', '7/7', (SELECT COUNT_IF(TYPOLOGY='AML_LAYERING')||'/'||COUNT(*) FROM truth WHERE SCENARIO='STRUCTURING')
UNION ALL SELECT 'DETECTION: round-trip recall', '6/6', (SELECT COUNT_IF(TYPOLOGY='AML_LAYERING')||'/'||COUNT(*) FROM truth WHERE SCENARIO='ROUND_TRIP')
UNION ALL SELECT 'DETECTION: false positives on clean accounts', '0', (SELECT COUNT(*)::STRING FROM RISK_COPILOT.CURATED.DT_FRAUD_ALERTS a WHERE a.ACCOUNT_ID NOT IN (SELECT ACCOUNT_ID FROM RISK_COPILOT.RAW.SYNTH_SCENARIOS))
UNION ALL SELECT 'EXPLAINABILITY: every red flag maps to an existing policy section', '0 unmapped',
  (SELECT COUNT(*)||' unmapped' FROM RISK_COPILOT.CURATED.DT_FRAUD_ALERTS a, LATERAL FLATTEN(a.RED_FLAGS) f
    WHERE NOT EXISTS (SELECT 1 FROM RISK_COPILOT.RAW.POLICY_DOCS p WHERE STARTSWITH(p.SECTION, REGEXP_REPLACE(f.value:policy::STRING, '\\([a-z]\\)$', ''))))
UNION ALL SELECT 'DATA: transactions reference valid accounts', '0 orphans',
  (SELECT COUNT(*)||' orphans' FROM RISK_COPILOT.RAW.TRANSACTIONS t WHERE NOT EXISTS (SELECT 1 FROM RISK_COPILOT.RAW.ACCOUNTS a WHERE a.ACCOUNT_ID=t.ACCOUNT_ID))
UNION ALL SELECT 'DATA: no duplicate transaction IDs', '0', (SELECT (COUNT(*)-COUNT(DISTINCT TXN_ID))::STRING FROM RISK_COPILOT.RAW.TRANSACTIONS)
UNION ALL SELECT 'CREDIT: SMA class consistent with DPD', '0 mismatches',
  (SELECT COUNT(*)||' mismatches' FROM RISK_COPILOT.CURATED.DT_LOAN_EWS WHERE (ASSET_CLASS='SMA-0' AND DPD NOT BETWEEN 1 AND 30) OR (ASSET_CLASS='SMA-1' AND DPD NOT BETWEEN 31 AND 60) OR (ASSET_CLASS='SMA-2' AND DPD NOT BETWEEN 61 AND 90) OR (ASSET_CLASS='NPA' AND DPD <= 90) OR (ASSET_CLASS='STANDARD' AND DPD<>0))
UNION ALL SELECT 'LIQUIDITY: Level 2 share <= 40% of HQLA', '0 breaches',
  (SELECT COUNT(*)||' breaches' FROM lcr WHERE (HQLA_STOCK - L1_HQLA) > 0.4*HQLA_STOCK + 1)
UNION ALL SELECT 'LIQUIDITY: status consistent with LCR thresholds', '0 mismatches',
  (SELECT COUNT(*)||' mismatches' FROM lcr WHERE LCR_STATUS <> CASE WHEN LCR_PCT<100 THEN 'REGULATORY_BREACH' WHEN LCR_PCT<110 THEN 'RED_CFP_TRIGGER' WHEN LCR_PCT<115 THEN 'AMBER_ALCO' ELSE 'GREEN' END)
UNION ALL SELECT 'GUARDRAIL: fabricated clauses are caught', '["Section 45-IA","[AML-POL 9.9]"]',
  RISK_COPILOT.APP.VALIDATE_CITATIONS('See Section 45-IA and [AML-POL 9.9] and [AML-POL 4.2(c)]', ARRAY_CONSTRUCT(), ARRAY_CONSTRUCT('AML-POL 4.2 Money Mule Red Flags'), '')::STRING
UNION ALL SELECT 'GUARDRAIL: grounded clauses pass', '[]',
  RISK_COPILOT.APP.VALIDATE_CITATIONS('Per [AML-POL 4.2(a)] and [AML-POL 6.1]', ARRAY_CONSTRUCT('[AML-POL 4.2]'), ARRAY_CONSTRUCT('AML-POL 4.2 Money Mule Red Flags','AML-POL 6.1 STR Filing Timeline'), '')::STRING
UNION ALL SELECT 'GOVERNANCE: every case requires human review', '0 without', (SELECT COUNT_IF(GUARDRAIL_RESULT:human_review_required::BOOLEAN IS DISTINCT FROM TRUE)||' without' FROM RISK_COPILOT.APP.CASES);

-- Validation results with PASS/FAIL
CREATE OR REPLACE VIEW V_VALIDATION_RESULTS AS
SELECT TEST, EXPECTED, ACTUAL,
  IFF(EXPECTED = ACTUAL OR (TRY_PARSE_JSON(EXPECTED) IS NOT NULL AND ARRAY_SORT(TRY_PARSE_JSON(EXPECTED)::ARRAY) = ARRAY_SORT(TRY_PARSE_JSON(ACTUAL)::ARRAY)), 'PASS', 'FAIL') AS RESULT
FROM RISK_COPILOT.APP.V_VALIDATION_TESTS;
