-- =============================================================================
-- 02: RAW schema tables (source / landing zone)
-- =============================================================================
USE SCHEMA RISK_COPILOT.RAW;

CREATE OR REPLACE TABLE ACCOUNTS (
    ACCOUNT_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    ACCOUNT_TYPE VARCHAR(7),
    OPEN_DATE DATE,
    STATUS VARCHAR(6),
    CURRENT_BALANCE NUMBER(7,0)
);

CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID VARCHAR,
    FULL_NAME VARCHAR,
    SEGMENT VARCHAR(10),
    KYC_RISK_RATING VARCHAR,
    CITY VARCHAR,
    IS_PEP BOOLEAN,
    ONBOARDED_DATE DATE,
    OCCUPATION VARCHAR,
    DECLARED_ANNUAL_INCOME NUMBER(7,0)
);

CREATE OR REPLACE TABLE TRANSACTIONS (
    TXN_ID VARCHAR,
    ACCOUNT_ID VARCHAR,
    COUNTERPARTY_ACCOUNT_ID VARCHAR,
    TXN_TS TIMESTAMP_NTZ,
    CHANNEL VARCHAR(4),
    DIRECTION VARCHAR(6),
    AMOUNT_INR FLOAT,
    DEVICE_ID VARCHAR,
    IP_ADDRESS VARCHAR,
    GEO_COUNTRY VARCHAR(2),
    SYNTH_LABEL VARCHAR(30)
);

CREATE OR REPLACE TABLE LOANS (
    LOAN_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    SEGMENT VARCHAR(10),
    PRODUCT VARCHAR,
    INDUSTRY VARCHAR,
    SANCTIONED_LIMIT NUMBER(10,0),
    DISBURSAL_DATE DATE,
    INTEREST_RATE FLOAT,
    COLLATERAL_TYPE VARCHAR,
    BUREAU_SCORE NUMBER(3,0),
    OUTSTANDING NUMBER(18,0),
    UTILIZATION_PCT FLOAT,
    DPD NUMBER(3,0),
    NACH_BOUNCES_90D NUMBER(2,0),
    SALES_VELOCITY_CHG_PCT FLOAT
);

CREATE OR REPLACE TABLE CASHFLOW_POSITIONS (
    AS_OF_DATE DATE,
    CATEGORY VARCHAR(37),
    FLOW_TYPE VARCHAR(7),
    RATE FLOAT,
    BUCKET VARCHAR(6),
    BALANCE_INR FLOAT
);

CREATE OR REPLACE TABLE HQLA_HOLDINGS (
    AS_OF_DATE DATE,
    INSTRUMENT VARCHAR(19),
    HQLA_LEVEL VARCHAR(8),
    HAIRCUT FLOAT,
    MARKET_VALUE_INR FLOAT
);

CREATE OR REPLACE TABLE POLICY_DOCS (
    DOC_ID VARCHAR,
    DOC_TITLE VARCHAR,
    DOC_TYPE VARCHAR,
    SECTION VARCHAR,
    DOMAIN VARCHAR,
    EFFECTIVE_DATE DATE,
    CHUNK_TEXT VARCHAR
);

CREATE OR REPLACE TABLE WATCHLIST (
    LIST_NAME VARCHAR,
    ENTITY_NAME VARCHAR,
    MATCHED_CUSTOMER_ID VARCHAR,
    MATCH_SCORE FLOAT,
    LISTED_DATE DATE,
    REMARKS VARCHAR
);

CREATE OR REPLACE TABLE SYNTH_SCENARIOS (
    ACCOUNT_ID VARCHAR,
    CUSTOMER_ID VARCHAR,
    SCENARIO VARCHAR(11)
);
